version: '3'

tasks:
  generate:
    cmds:
      - go install github.com/atombender/go-jsonschema@latest
      - go-jsonschema -p internal/api resources/schema.json > pkg/api/generated_api.go

  test:
    cmds:
      - go test ./... -v --failfast

  lint:
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin
      - $GOPATH/bin/golangci-lint run -v -c .golangci.yml ./...